[workspace]
members = ["app", "cleaner"]

resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.9"
authors = ["ziprangga"]
license = "Apache-2.0"

[workspace.dependencies]
# ====================
cleaner = { path = "cleaner" }
# ====================
plist = "1.3"
walkdir = "2.3"
rayon = "1.11"
sysinfo = "0.37"

# ====================
mini-logger = { git = "https://github.com/ziprangga/mini-logger.git", default-features = false, tag = "v0.1.5"}
simple-status = { git = "https://github.com/ziprangga/simple-status.git", tag = "v0.1.10"}
tokio = { version = "1.49", features = ["full"] }
rfd = "0.17"
unicode-normalization = "0.1"
iced = { git = "https://github.com/ziprangga/iced.git", features = [
    "image-without-codecs",
    "tokio",
    "canvas",
    "wgpu",
    "advanced",
] }

# =======System=======
objc2 = "0.6"
objc2-foundation = { version = "0.3", features = ["NSFileManager", "NSURL", "NSArray", "NSString", "NSError", "NSData",] }
objc2-app-kit = { version = "0.3", features = ["NSWorkspace", "NSImage", "NSBitmapImageRep", "objc2-uniform-type-identifiers"] }
objc2-uniform-type-identifiers = { version = "0.3", features = ["UTType"] }
libc = "0.2"


# ======profile=======
[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
lto = false
codegen-units = 16
