// Copyright 2026 ziprangga
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Doc:
//! Native macOS icon and image utilities.
//!
//! Provides helpers for retrieving system icons and converting
//! Cocoa image types into raw pixel buffers suitable for Rust UI
//! frameworks.
//!
//! Supported icon sources include:
//!
//! - Installed applications.
//! - System folders.
//! - Generic file types.
//!
//! Note:
//! These helpers are primarily consumed by `IconCache`.
//!..

use objc2::AnyThread;
use objc2::rc::Retained;
use objc2_app_kit::{NSBitmapImageRep, NSGraphicsContext, NSImage, NSWorkspace};
use objc2_foundation::{NSAutoreleasePool, NSPoint, NSRect, NSSize, NSString};
use objc2_uniform_type_identifiers::{UTTypeFolder, UTTypeItem};

/// Returns the system folder icon.
///
/// Doc:
/// Retrieves the default folder icon provided by macOS.
///
/// The returned icon corresponds to the system-defined
/// representation of a generic folder.
///
/// Note:
/// The returned image is owned through Objective-C reference
/// counting and can be safely passed to image conversion
/// utilities.
pub fn get_default_folder_icon() -> Retained<NSImage> {
    let pool = unsafe { NSAutoreleasePool::new() };
    let result = {
        let workspace = NSWorkspace::sharedWorkspace();
        // UTTypeFolder represents the identifier "public.folder"
        workspace.iconForContentType(unsafe { &UTTypeFolder })
    };

    drop(pool);
    result
}

/// Returns the system generic file icon.
///
/// Doc:
/// Retrieves the default icon used by macOS when no
/// application-specific icon is available.
///
/// Note:
/// This icon is shared across generic file types and serves as
/// a fallback representation.
pub fn get_default_file_icon() -> Retained<NSImage> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = {
        let workspace = NSWorkspace::sharedWorkspace();
        workspace.iconForContentType(unsafe { &UTTypeItem })
    };

    drop(pool);
    result
}

/// Retrieves an application's icon.
///
/// Doc:
/// Returns the icon associated with an installed application
/// bundle.
///
/// The icon is resolved using the same mechanisms employed by
/// Finder and Launch Services.
///
/// Design:
/// Icon lookup is delegated to `NSWorkspace` so the operating
/// system can select the correct icon resource and resolution.
///
/// This avoids manually parsing application bundle resources.
///
/// Note:
/// The provided path should reference an application bundle.
pub fn get_installed_app_icon_by_path(app_path: &str) -> Retained<NSImage> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = {
        let workspace = NSWorkspace::sharedWorkspace();
        let path_ns = NSString::from_str(app_path);
        // Uses the safe, autogenerated instance method wrapper from objc2-app-kit
        workspace.iconForFile(&path_ns)
    };

    drop(pool);
    result
}

/// Converts an `NSImage` into RGBA pixel data.
///
/// Doc:
/// Renders an `NSImage` into a fixed-size bitmap and returns:
///
/// - Width.
/// - Height.
/// - RGBA bytes.
///
/// The resulting pixel buffer can be used by Rust UI
/// frameworks and image-processing code.
///
/// Design:
/// macOS icons are often lazily rendered and may contain
/// multiple embedded resolutions.
///
/// Rather than reading bitmap representations directly, a new
/// offscreen bitmap buffer is created and the image is asked to
/// render itself into that buffer.
///
/// This ensures:
///
/// - Consistent dimensions.
/// - Predictable RGBA output.
/// - Correct scaling behavior.
/// - Elimination of uninitialized backing storage.
///
/// The operating system automatically selects the most
/// appropriate icon representation during rendering.
///
/// Note:
/// The returned pixel data is tightly packed RGBA with
/// 8 bits per channel.
pub fn ns_image_to_rgba_bytes(
    image: &NSImage,
    target_size: f64,
) -> Option<(usize, usize, Vec<u8>)> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = (|| -> Option<(usize, usize, Vec<u8>)> {
        let width = target_size as usize;
        let height = target_size as usize;

        // Force allocate a brand new, clean offscreen bitmap buffer
        // This cuts away the uninitialized/lazy baggage from iconForFile
        let bitmap_rep = unsafe {
            NSBitmapImageRep::initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel(
                NSBitmapImageRep::alloc(),
                std::ptr::null_mut(), // macOS allocates clean memory automatically
                width as isize,
                height as isize,
                8,                    // 8 bits per channel
                4,                    // 4 channels (RGBA)
                true,                 // has alpha
                false,                // interleaved, not planar
                objc2_app_kit::NSCalibratedRGBColorSpace,
                (width * 4) as isize, // Strict row byte pitch alignment
                32,                   // 32 bits per pixel total
            )?
        };

        // Lock a temporary Cocoa graphics rendering context onto our clean bitmap buffer
        let context = NSGraphicsContext::graphicsContextWithBitmapImageRep(&bitmap_rep)?;
        NSGraphicsContext::setCurrentContext(Some(&context));

        // Force the application icon to draw itself directly onto our target sizing box
        let target_rect = NSRect::new(
            NSPoint::new(0.0, 0.0),
            NSSize::new(target_size, target_size),
        );

        // This safely chooses the best scaling algorithm out of the app's multiple sizes
        image.drawInRect(target_rect);

        // Pop the graphics context back to normal safely
        NSGraphicsContext::setCurrentContext(None);

        // Read the clean pixels out safely
        let bitmap_ptr = bitmap_rep.bitmapData();
        if bitmap_ptr.is_null() {
            return None;
        }

        let total_bytes = width * height * 4;
        let raw_slice = unsafe { std::slice::from_raw_parts(bitmap_ptr, total_bytes) };

        // Copy the unpadded, cleanly flattened vector
        let rgba_bytes = raw_slice.to_vec();

        Some((width, height, rgba_bytes))
    })();

    drop(pool);
    result
}
