// Copyright 2026 ziprangga
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Doc:
//! BOM inspection helpers.
//!
//! Provides utilities for reading and exporting information
//! from macOS Bill of Materials (BOM) files.
//!
//! BOM files are commonly generated by package installers and
//! describe files installed by a package.
//!
//! Note:
//! These helpers depend on the system `lsbom` utility.
//!..

use std::fs::File;
use std::io::Write;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result};

/// Exports a BOM file to a text log.
///
/// Doc:
/// Executes the macOS `lsbom` utility and writes the resulting
/// file listing to the specified output file.
///
/// Design:
/// The implementation delegates BOM parsing to Apple's
/// official tooling rather than attempting to interpret the
/// BOM format directly.
///
/// This ensures compatibility with system-generated BOM files
/// while keeping maintenance requirements low.
///
/// Note:
/// An error is returned when:
///
/// - `lsbom` cannot be executed.
/// - The BOM file is invalid.
/// - The output file cannot be written.
pub fn run_lsbom_command(bom_file: &Path, output_file: &Path) -> Result<()> {
    let bom_file_str = bom_file.to_string_lossy();

    let output = Command::new("lsbom")
        .args(["-f", "-l", "-s", "-p", "f", &bom_file_str])
        .output()
        .with_context(|| format!("Failed to run lsbom on {}", bom_file.display()))?;

    if output.status.success() {
        let mut f = File::create(output_file)
            .with_context(|| format!("Failed to create file: {}", output_file.display()))?;
        f.write_all(&output.stdout)
            .with_context(|| format!("Failed to write BOM log: {}", output_file.display()))?;
        println!("Saved BOM log: {}", output_file.display());
        Ok(())
    } else {
        anyhow::bail!(
            "lsbom failed for {}: {}",
            bom_file.display(),
            String::from_utf8_lossy(&output.stderr)
        )
    }
}
