use objc2::rc::Retained;
use objc2_app_kit::{NSBitmapImageRep, NSImage, NSWorkspace};
use objc2_foundation::NSSize;
use objc2_foundation::{NSAutoreleasePool, NSString};
use objc2_uniform_type_identifiers::UTType;

pub struct RawIcon {
    pub width: usize,
    pub height: usize,
    pub rgba_bytes: Vec<u8>,
}

/// 1. Fetch generic system icons SAFELY using built-in methods
pub fn get_generic_system_icon(icon_name: &str) -> Option<Retained<NSImage>> {
    let name_ns = NSString::from_str(icon_name);
    // Uses the safe, autogenerated class method wrapper from objc2-app-kit
    NSImage::imageNamed(&name_ns)
}

/// 2. Fetch installed app icons SAFELY using built-in methods
pub fn get_installed_app_icon(app_path: &str) -> Retained<NSImage> {
    let workspace = NSWorkspace::sharedWorkspace();
    let path_ns = NSString::from_str(app_path);
    // Uses the safe, autogenerated instance method wrapper from objc2-app-kit
    workspace.iconForFile(&path_ns)
}

/// 3. Convert the image to bytes SAFELY using official crate methods
pub fn ns_image_to_rgba_bytes(image: &NSImage, target_size: f64) -> Option<RawIcon> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = (|| -> Option<RawIcon> {
        // Rescale the image safely using standard Rust methods
        let size = NSSize::new(target_size, target_size);
        image.setSize(size);

        // Extract the CoreGraphics representation safely
        // Passing null pointers safely via standard Rust Option/std::ptr
        // let cg_image = image.CGImageForProposedRect_context_hints(
        //     std::ptr::null_mut(),
        //     std::ptr::null_mut(),
        //     std::ptr::null_mut(),
        // )?;

        // 3. Initialize the bitmap wrapper safely without alloc() + init() macros
        // let bitmap_rep = unsafe {
        //     // NOTE: initWithCGImage is one of the few places where objc2 still forces
        //     // an unsafe boundary due to raw CoreGraphics pointer tracking,
        //     // but it is an official crate method instead of a custom msg_send! macro.
        //     NSBitmapImageRep::initWithCGImage(NSBitmapImageRep::alloc(), cg_image)?
        // };

        let tiff_bytes = image.TIFFRepresentation()?;
        let bitmap_rep = NSBitmapImageRep::imageRepWithData(&tiff_bytes)?;

        // Query the image properties via safe, native Rust getters
        let width = bitmap_rep.pixelsWide() as usize;
        let height = bitmap_rep.pixelsHigh() as usize;

        let bytes_per_row = bitmap_rep.bytesPerRow() as usize;
        let bits_per_pixel = bitmap_rep.bitsPerPixel() as usize;
        let bytes_per_pixel = bits_per_pixel / 8;

        // Safely pull the raw data pointer
        let bitmap_data_ptr = bitmap_rep.bitmapData();
        if bitmap_data_ptr.is_null() {
            return None;
        }

        // Copy the bytes directly into our Rust vector
        // let total_bytes = width * height * 4;
        // let mut rgba_bytes = vec![0u8; total_bytes];

        let total_allocated_bytes = bytes_per_row * height;

        // unsafe {
        //     std::ptr::copy_nonoverlapping(bitmap_data_ptr, rgba_bytes.as_mut_ptr(), total_bytes);
        // }

        let raw_slice =
            unsafe { std::slice::from_raw_parts(bitmap_data_ptr, total_allocated_bytes) };

        let mut rgba_bytes = Vec::with_capacity(width * height * bytes_per_pixel);

        for row in 0..height {
            let start = row * bytes_per_row;
            let end = start + width * bytes_per_pixel;
            rgba_bytes.extend_from_slice(&raw_slice[start..end]);
        }

        Some(RawIcon {
            width,
            height,
            rgba_bytes,
        })
    })();

    drop(pool);
    result
}
