use objc2::AnyThread;
use objc2::rc::Retained;
use objc2_app_kit::{NSBitmapImageRep, NSGraphicsContext, NSImage, NSWorkspace};
use objc2_foundation::{NSAutoreleasePool, NSPoint, NSRect, NSSize, NSString};
use objc2_uniform_type_identifiers::{UTTypeFolder, UTTypeItem};

pub fn get_default_folder_icon() -> Retained<NSImage> {
    let pool = unsafe { NSAutoreleasePool::new() };
    let result = {
        let workspace = NSWorkspace::sharedWorkspace();
        // UTTypeFolder represents the identifier "public.folder"
        workspace.iconForContentType(unsafe { &UTTypeFolder })
    };

    drop(pool);
    result
}

pub fn get_default_file_icon() -> Retained<NSImage> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = {
        let workspace = NSWorkspace::sharedWorkspace();
        workspace.iconForContentType(unsafe { &UTTypeItem })
    };

    drop(pool);
    result
}

/// Fetch installed app icons SAFELY using built-in methods
pub fn get_installed_app_icon_by_path(app_path: &str) -> Retained<NSImage> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = {
        let workspace = NSWorkspace::sharedWorkspace();
        let path_ns = NSString::from_str(app_path);
        // Uses the safe, autogenerated instance method wrapper from objc2-app-kit
        workspace.iconForFile(&path_ns)
    };

    drop(pool);
    result
}

pub fn ns_image_to_rgba_bytes(
    image: &NSImage,
    target_size: f64,
) -> Option<(usize, usize, Vec<u8>)> {
    let pool = unsafe { NSAutoreleasePool::new() };

    let result = (|| -> Option<(usize, usize, Vec<u8>)> {
        let width = target_size as usize;
        let height = target_size as usize;

        // Force allocate a brand new, clean offscreen bitmap buffer
        // This cuts away the uninitialized/lazy baggage from iconForFile
        let bitmap_rep = unsafe {
            NSBitmapImageRep::initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel(
                NSBitmapImageRep::alloc(),
                std::ptr::null_mut(), // macOS allocates clean memory automatically
                width as isize,
                height as isize,
                8,                    // 8 bits per channel
                4,                    // 4 channels (RGBA)
                true,                 // has alpha
                false,                // interleaved, not planar
                objc2_app_kit::NSCalibratedRGBColorSpace,
                (width * 4) as isize, // Strict row byte pitch alignment
                32,                   // 32 bits per pixel total
            )?
        };

        // Lock a temporary Cocoa graphics rendering context onto our clean bitmap buffer
        let context = NSGraphicsContext::graphicsContextWithBitmapImageRep(&bitmap_rep)?;
        NSGraphicsContext::setCurrentContext(Some(&context));

        // Force the application icon to draw itself directly onto our target sizing box
        let target_rect = NSRect::new(
            NSPoint::new(0.0, 0.0),
            NSSize::new(target_size, target_size),
        );

        // This safely chooses the best scaling algorithm out of the app's multiple sizes
        image.drawInRect(target_rect);

        // Pop the graphics context back to normal safely
        NSGraphicsContext::setCurrentContext(None);

        // Read the clean pixels out safely
        let bitmap_ptr = bitmap_rep.bitmapData();
        if bitmap_ptr.is_null() {
            return None;
        }

        let total_bytes = width * height * 4;
        let raw_slice = unsafe { std::slice::from_raw_parts(bitmap_ptr, total_bytes) };

        // Copy the unpadded, cleanly flattened vector
        let rgba_bytes = raw_slice.to_vec();

        Some((width, height, rgba_bytes))
    })();

    drop(pool);
    result
}
